### ISSUE TITLE
Input CSV cannot be parsed correctly if first 1,000 rows are missing lat or lon

### ISSUE THREAD

**Issue by sneharav15** [degauss-org/census_block_group#17]
**1. When I run geocoding on ~5000 rows of data and then run the census tract – the census tract container works fine on the geocoded file and there are no parsing issues. Command line below, all fine:**

docker run --rm -v $PWD:/tmp ghcr.io/degauss-org/census_block_group:0.4.2 pedsnet_v1_10001to15000rows_geocoded_v3.0.2.csv 2020

── Wecome to DeGAUSS! ──────────────────────────────────────────────────────────
ℹ You are using the census_block_group container, version 0.4.2.
This container adds census block group or tract identifiers to geocoded
addresses.
For more information about the census_block_group container, visit
<https://degauss.org/census_block_group/>
For DeGAUSS troubleshooting, visit <https://degauss.org/>
To help us improve DeGAUSS, please take our user survey at
<https://degauss.org/survey>

reading input file...

── Column specification ────────────────────────────────────────────────────────
cols(
  location_id = col_double(),
  person_id = col_double(),
  address = col_character(),
  matched_street = col_character(),
  matched_zip = col_double(),
  matched_city = col_character(),
  matched_state = col_character(),
  lat = col_double(),
  lon = col_double(),
  score = col_double(),
  precision = col_character(),
  geocode_result = col_character()
)

loading census shape files...

finding containing geography for each point...
Warning message:
attribute variables are assumed to be spatially constant throughout all geometries 

FINISHED! output written to pedsnet_v1_10001to15000rows_geocoded_v3.0.2_census_block_group_2020.csv

**2. When I run 10000 rows of data through the geocoder, I get an output that looks the same as the 5000 rows (with more rows), but the census tract container fails with the parsing errors below, and the execution halts. If I split the 10,000 row geocoded output file into 2 5000 files, I also get the same parsing errors. I don’t see any issues with the rows though, and the outputs of the two look exactly the same, so I do not know what is going on with the geocoder output which causes the census tract container to fail.**

Error message:
docker run --rm -v $PWD:/tmp ghcr.io/degauss-org/census_block_group:0.4.2 pedsnet_v1_10001to20000rows_geocoded_v3.0.2.csv 2020

── Wecome to DeGAUSS! ──────────────────────────────────────────────────────────
ℹ You are using the census_block_group container, version 0.4.2.
This container adds census block group or tract identifiers to geocoded
addresses.
For more information about the census_block_group container, visit
<https://degauss.org/census_block_group/>
For DeGAUSS troubleshooting, visit <https://degauss.org/>
To help us improve DeGAUSS, please take our user survey at
<https://degauss.org/survey>

reading input file...

── Column specification ────────────────────────────────────────────────────────
cols(
  location_id = col_double(),
  person_id = col_double(),
  address = col_character(),
  matched_street = col_character(),
  matched_zip = col_double(),
  matched_city = col_character(),
  matched_state = col_character(),
  lat = col_logical(),
  lon = col_logical(),
  score = col_double(),
  precision = col_character(),
  geocode_result = col_character()
)

Warning: 17876 parsing failures.
 row col           expected              actual                                              file
1062 lat 1/0/T/F/TRUE/FALSE 37.663568           'pedsnet_v1_10001to20000rows_geocoded_v3.0.2.csv'
1062 lon 1/0/T/F/TRUE/FALSE -120.98134400000001 'pedsnet_v1_10001to20000rows_geocoded_v3.0.2.csv'
1063 lat 1/0/T/F/TRUE/FALSE 37.663568           'pedsnet_v1_10001to20000rows_geocoded_v3.0.2.csv'
1063 lon 1/0/T/F/TRUE/FALSE -120.98134400000001 'pedsnet_v1_10001to20000rows_geocoded_v3.0.2.csv'
1064 lat 1/0/T/F/TRUE/FALSE 37.468057           'pedsnet_v1_10001to20000rows_geocoded_v3.0.2.csv'
.... ... .................. ................... .................................................
See problems(...) for more details.

Warning messages:
1: In min(cc[[1]], na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
2: In min(cc[[2]], na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
3: In max(cc[[1]], na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
4: In max(cc[[2]], na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf

loading census shape files...

finding containing geography for each point...
Warning message:
attribute variables are assumed to be spatially constant throughout all geometries 
Error: Join columns must be present in data.
✖ Problem with `.row`.
Backtrace:
    █
 1. ├─left_join(raw_data, d, by = ".row") %>% select(-.row)
 2. ├─dplyr::select(., -.row)
 3. ├─dplyr::left_join(raw_data, d, by = ".row")
 4. └─dplyr:::left_join.data.frame(raw_data, d, by = ".row")
 5.   └─dplyr:::join_mutate(...)
 6.     └─dplyr:::join_cols(...)
 7.       └─dplyr:::standardise_join_by(by, x_names = x_names, y_names = y_names)
 8.         └─dplyr:::check_join_vars(by$y, y_names)
Execution halted

I will upload files for both the 5000 rows and 10,000 rows, if they can be removed after the issue is fixed. Thank you!

**Comment by cole-brokamp** [comment]
Thanks for sending the files over privately.  I haven't tried myself, but I think what is happening is that the R code which reads the CSV file (https://github.com/degauss-org/census_block_group/blob/13a8a61addcd98ab8fdf38bca6f6ac53d2b275d1/census_block_group.R#L29-L30) uses the first 1,000 rows by default.  So, if the first 1,000 rows are all missing for lat or lon, then `readr` assumes its is of type logical and will not be able to read in numeric values later on, thus giving the problem where there are no values read in.

You can fix this by first removing the missing geocodes before running them through the container.  The software itself ignores the missing location data and returns it as it was in the input file.  This is designed for convenience and I hope to still make this possible, but for now if you can ensure that at least one of your first 1,000 rows is not missing lat/lon, then it will be able to correctly read in the file and solve your issue.

Also worth noting that newer versions of {readr} use {vroom} to read CSV files and will always consult the last row in addition to the first 1,000.  That usually fixes the issue, as the geocoder puts all missing geocodes at the top of the file, but your example geocoded file seemed to have an extra line added at the end.

Long term (@erikarasnick), we should probably enforce column types in the code since we already know that lat/lon should be numeric -- this would prevent the parsing problem from ever being an issue.

**Comment by cole-brokamp** [comment]
via email

> Thanks for the fix on the previous issue – removing the NA rows has fixed the issue with the census tract.
